#!/usr/bin/env node
'use strict';

/**
 * Bakes data/pyq/** into pyq/data.js.
 *
 * The site needs to read the archive with no server. `fetch()` on a JSON file
 * is blocked by CORS under file://, so opening pyq/index.html by double-click
 * would show an empty archive — which is exactly how most contributors will
 * first look at their own change. Baking the data into a plain <script> keeps
 * that working, at the cost of one generated file that CI checks is in sync.
 *
 * Usage: node build.js
 */

const fs = require('fs');
const path = require('path');

const PYQ = require('./src/pyq.js');

const REPO_ROOT = __dirname;
const OUTPUT = path.join(REPO_ROOT, 'pyq', 'data.js');

function readJson(relativePath) {
  const absolutePath = path.join(REPO_ROOT, relativePath);
  if (!fs.existsSync(absolutePath)) return null;
  try {
    return JSON.parse(fs.readFileSync(absolutePath, 'utf8'));
  } catch (error) {
    console.error('Cannot parse ' + relativePath + ': ' + error.message);
    process.exit(1);
  }
}

const catalogue = readJson(PYQ.DATA_DIR + '/catalogue.json');
if (!catalogue) {
  console.error('Missing ' + PYQ.DATA_DIR + '/catalogue.json — nothing to build.');
  process.exit(1);
}

/**
 * A collection with no file yet is a legitimate state, not an error: most
 * branches start empty and gain papers as people contribute. It bakes as an
 * empty array so the site renders its "nothing here yet" state rather than
 * breaking on an undefined lookup.
 */
const collections = {};
let paperCount = 0;

PYQ.expectedCollections(catalogue).forEach(function (collection) {
  const relativePath = PYQ.collectionPath(collection.programmeId, collection.year, collection.branchId);
  const papers = readJson(relativePath) || [];

  if (!Array.isArray(papers)) {
    console.error(relativePath + ': expected an array of papers, got ' + typeof papers);
    process.exit(1);
  }

  collections[collection.key] = PYQ.sortPapers(papers);
  paperCount += papers.length;
});

const banner = [
  '// Generated by build.js from ' + PYQ.DATA_DIR + '/ — do not edit by hand.',
  '// Edit the JSON under ' + PYQ.DATA_DIR + '/, then run: node build.js',
  "'use strict';",
  '',
].join('\n');

// A missing subjects.json is survivable — the picker falls back to the
// subjects already present in the archive — so it warns rather than exits.
const subjectsFile = readJson(PYQ.DATA_DIR + '/subjects.json');
if (!subjectsFile) console.warn('No ' + PYQ.DATA_DIR + '/subjects.json — the subject picker will offer only what the archive already holds.');

const payload = {
  catalogue: catalogue,
  collections: collections,
  subjects: (subjectsFile && subjectsFile.subjects) || {},
};

const output = banner + 'window.PYQ_DATA = ' + JSON.stringify(payload, null, 2) + ';\n';

fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });
fs.writeFileSync(OUTPUT, output, 'utf8');

console.log(
  'Wrote pyq/data.js — ' +
    Object.keys(collections).length +
    ' collections, ' +
    paperCount +
    ' paper' +
    (paperCount === 1 ? '' : 's') +
    '.'
);
