#!/usr/bin/env node
'use strict';

/**
 * Generates assets/fonts/fonts.css from the .woff2 files beside it, embedding
 * each face as a data: URI.
 *
 * Why embed rather than link the .woff2 directly: font fetches are always made
 * in CORS mode, and a browser refuses a cross-origin font under file:// — the
 * origin is `null`, so a page opened by double-click silently falls back to
 * system faces and the design system doesn't render. Everywhere else in this
 * repo we bend to "you must be able to double-click index.html and have it
 * work", and the brand is not the place to stop.
 *
 * The cost is ~33% size inflation over the wire and a large generated file. It
 * is marked linguist-generated so it collapses in diffs, and this script makes
 * it reproducible rather than hand-maintained.
 *
 * Usage: node build-fonts.js
 */

const fs = require('fs');
const path = require('path');

const FONT_DIR = path.join(__dirname, 'assets', 'fonts');
const OUTPUT = path.join(FONT_DIR, 'fonts.css');

/**
 * The latin subset's unicode-range, copied from the Google Fonts CSS these
 * files came from. Keeping it means a character outside the subset falls
 * through to the next font in the stack rather than rendering as tofu.
 */
const LATIN_RANGE =
  'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2122, U+2212, U+FEFF, U+FFFD';

const FACES = [
  { family: 'Anton', file: 'anton-latin.woff2', weight: '400' },
  { family: 'Space Grotesk', file: 'space-grotesk-latin.woff2', weight: '400 700' },
  { family: 'JetBrains Mono', file: 'jetbrains-mono-latin.woff2', weight: '400 700' },
];

const blocks = FACES.map(function (face) {
  const absolute = path.join(FONT_DIR, face.file);

  if (!fs.existsSync(absolute)) {
    console.error('Missing ' + path.relative(__dirname, absolute) + ' — see assets/fonts/README.md.');
    process.exit(1);
  }

  const base64 = fs.readFileSync(absolute).toString('base64');

  return [
    '@font-face {',
    '  font-family: "' + face.family + '";',
    '  font-style: normal;',
    '  font-weight: ' + face.weight + ';',
    '  font-display: swap;',
    '  src: url(data:font/woff2;base64,' + base64 + ') format("woff2");',
    '  unicode-range: ' + LATIN_RANGE + ';',
    '}',
  ].join('\n');
});

const banner = [
  '/*',
  ' * Generated by build-fonts.js from the .woff2 files in this directory.',
  ' * Do not edit by hand — run: node build-fonts.js',
  ' *',
  ' * Faces are embedded as data: URIs so they load under file:// as well as',
  ' * over HTTP. All three are SIL OFL 1.1; see README.md in this directory.',
  ' */',
  '',
].join('\n');

fs.writeFileSync(OUTPUT, banner + blocks.join('\n\n') + '\n', 'utf8');

const kilobytes = Math.round(fs.statSync(OUTPUT).size / 1024);
console.log('Wrote assets/fonts/fonts.css — ' + FACES.length + ' faces, ' + kilobytes + ' KB.');
